language: node_js
node_js:
  - 12

services:
  - docker

before_install:
- docker-compose up -d
- cat db/scripts/schema.sql | docker run -i --rm --network larry-tracker_default --link larry-tracker_ch-server-1_1:ch-server-1 yandex/clickhouse-client -m --host ch-server-1 --database default --multiquery
- cat db/scripts/sample1.sql | docker run -i --rm --network larry-tracker_default --link larry-tracker_ch-server-1_1:ch-server-1 yandex/clickhouse-client -m --host ch-server-1 --database default --multiquery

script:
  - yarn
  - ./node_modules/mocha/bin/mocha --recursive "./api/src/*.test.js"